name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update Changelog
        run: npx standard-version --skip.bump --skip.tag

      - name: Push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add CHANGELOG.md
            git commit -m "chore(release): update changelog"
            git push
          else
            echo "No changes detected, skipping changelog update."
          fi